on: 
  workflow_dispatch:
    inputs:
      iterations:
        description: 'The number of requests (iterations) to be executed (required field for execution type iterations)'
        default: '1'
        type: string
        required: false
      durationSeconds:
        description: 'The duration of execution in seconds/minutes/hours (examples 1s/1m/1h)'
        default: '1s'
        type: string
        required: true
      preAllocatedVUs:
        description: 'The number of preallocated VUS (required field for execution type iterations)'
        default: '1'
        type: string
        required: true
      maxVUs:
        description: 'The maximum number of threads (VUS) to run with (concurrent executions, required field for execution type iterations)'
        default: '120'
        type: string
        required: true
        
jobs:
  k6_forward_label:
    name: K6 Tracking List Test Runner
    runs-on: ubuntu-latest
    # environment: ${{ inputs.env }}
    container: docker://golang:1.19-alpine

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Create config.json file for ${{inputs.execution_type}} execution type
        run: |
              rm config.json
              touch config.json
              echo "{
                \"scenarios\": {
                  \"example_scenario\": {
                    \"executor\": \"constant-arrival-rate\",
                    \"rate\": ${{ inputs.iterations }},
                    \"timeUnit\": \"${{ inputs.durationSeconds }}\",
                    \"duration\": \"${{ inputs.durationSeconds }}\",
                    \"preAllocatedVUs\": \"${{ inputs.preAllocatedVUs }}\",
                    \"maxVUs\": \"${{ inputs.maxVUs }}\"
                  }
                }
              }" >> config.json

      - name: Install xk6
        run: go install go.k6.io/xk6/cmd/xk6@latest
      
      - name: Build xk6 binary
        run: xk6 build --with github.com/szkiba/xk6-dotenv@latest --with github.com/avitalique/xk6-file@latest --replace go.buf.build/grpc/go/prometheus/prometheus=buf.build/gen/go/prometheus/prometheus/protocolbuffers/go@latest --replace go.buf.build/grpc/go/gogo/protobuf=buf.build/gen/go/gogo/protobuf/protocolbuffers/go@latest

      - name: Run k6 mts post tracking test
        run: ./k6 run --config config.json load_tests_scripts/as_useast_qa_mts_post_tracking_list.js
