on: 
  workflow_dispatch:
    inputs:
      baseURL:
        description: 'The base url of CSA API'
        type: choice
        options:
        - "https://api-qa.kloudship.com:96/api/v1/"
        - "https://api.kloudship.com:96/api/v1/"
      shipmentMode:
        description: 'Mode of shipment'
        type: choice
        options:
        - "Test"
        - "Live"
      iterations:
        description: 'The number of requests (iterations) to be executed (required field for execution type iterations)'
        default: '1'
        type: string
        required: false
      durationSeconds:
        description: 'The duration of execution in seconds/minutes/hours (examples 1s/1m/1h)'
        default: '1s'
        type: string
        required: true
      vUs:
        description: 'The number of preallocated VUS (required field for execution type iterations)'
        default: '1'
        type: string
        required: true
      apiAuthKey:
        description: 'The CSA API Token to use'
        type: string
        required: true
      carrierAccountId:
        description: 'Carrier Account id'
        default: ""
        type: string
        required: true
      locationId:
        description: 'The CSA location id of pickup location'
        default: ""
        type: string
        required: false
        
jobs:
  k6_forward_label:
    name: K6 POST Shipment Test Runner
    runs-on: ubuntu-latest
    #environment: ${{ inputs.env }}
    container: docker://golang:1.19-alpine

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Create config.json file
        run: |
              rm config.json
              touch config.json
              echo "{
                \"scenarios\": {
                  \"example_scenario\": {
                    \"executor\": \"shared-iterations\",
                    \"iterations\": ${{ inputs.iterations }},
                    \"maxDuration\": \"${{ inputs.durationSeconds }}\",
                    \"vus\": \"${{ inputs.vUs }}\"
                  }
                },
                \"csa\": {
                  \"baseURL\": \"${{ inputs.baseURL }}\",
                  \"carrierAccountId\": \"${{ inputs.carrierAccountId }}\",
                  \"locationId\": \"${{ inputs.locationId }}\",
                  \"shipmentMode\": \"${{ inputs.shipmentMode }}\",
                  \"token\": \"${{ inputs.apiAuthKey }}\"
                }
              }" >> config.json
      
      - name: Install xk6
        run: go install go.k6.io/xk6/cmd/xk6@latest
      
      - name: Build xk6 binary
        run: xk6 build --with github.com/szkiba/xk6-dotenv@latest --with github.com/avitalique/xk6-file@latest --replace go.buf.build/grpc/go/prometheus/prometheus=buf.build/gen/go/prometheus/prometheus/protocolbuffers/go@latest --replace go.buf.build/grpc/go/gogo/protobuf=buf.build/gen/go/gogo/protobuf/protocolbuffers/go@latest

      - name: Run k6 forward label test
        run: ./k6 run --config config.json load_tests_scripts/csa_post_shipment.js

      - uses: actions/checkout@v4
      - run: |
          git config --local user.email "kaushiky655@gmail.com"
          git config --local user.name "Yash Kaushik"
          git commit -a -m "Add changes"
          git push

      # - name: Commit files
      #   run: |
      #     git config --local user.email "kaushiky655@gmail.com"
      #     git config --local user.name "Yash Kaushik"
      #     git commit -a -m "Add changes"

      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}