on: 
  workflow_dispatch:
    inputs:
      baseURL:
        description: 'The base url of PHv3 API'
        type: choice
        options:
        - "https://packagehub-api-qa.visiblescm.com/v3.1/"
        - "https://visible-shipping-qa-api.azurewebsites.net/api/v3.1/"
        - "https://visible-shipping-qa-api-statging.azurewebsites.net/api/v3.1/"
      iterations:
        description: 'The number of requests (iterations) to be executed (required field for execution type iterations)'
        default: '1'
        type: string
        required: false
      durationSeconds:
        description: 'The duration of execution in seconds/minutes/hours (examples 1s/1m/1h)'
        default: '1s'
        type: string
        required: true
      vUs:
          description: 'The number of preallocated VUS (required field for execution type iterations)'
          default: '1'
          type: string
          required: true
      apiAuthKey:
        description: 'The PHv3 API Token to use'
        type: string
        required: true
      carrierAccountId:
          description: 'The number of requests (iterations) to be executed (required field for execution type iterations)'
          default: "71087ab5-4995-4206-ba6c-33614a120473"
          type: string
          required: false
        
jobs:
  k6_forward_label:
    name: K6 POST Shipment Test Runner
    runs-on: ubuntu-latest
    #environment: ${{ inputs.env }}
    container: docker://golang:1.19-alpine

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Create config.json file
        run: |
              rm config.json
              touch config.json
              echo "{
                \"scenarios\": {
                  \"example_scenario\": {
                    \"executor\": \"constant-arrival-rate\",
                    \"rate\": ${{ inputs.iterations }},
                    \"timeUnit\": \"${{ inputs.durationSeconds }}\",
                    \"duration\": \"${{ inputs.durationSeconds }}\",
                    \"preAllocatedVUs\": \"${{ inputs.vUs }}\",
                    \"maxVUs\": \"${{ inputs.vUs }}\"
                  }
                },
                \"phv3\": {
                  \"baseURL\": \"${{ inputs.baseURL }}\",
                  \"carrierAccountId\": \"${{ inputs.carrierAccountId }}\",
                  \"token\": \"${{ inputs.apiAuthKey }}\"
                }
              }" >> config.json
      
      - name: Install xk6
        run: go install go.k6.io/xk6/cmd/xk6@latest
      
      - name: Build xk6 binary
        run: xk6 build --with github.com/szkiba/xk6-dotenv@latest --with github.com/avitalique/xk6-file@latest --replace go.buf.build/grpc/go/prometheus/prometheus=buf.build/gen/go/prometheus/prometheus/protocolbuffers/go@latest --replace go.buf.build/grpc/go/gogo/protobuf=buf.build/gen/go/gogo/protobuf/protocolbuffers/go@latest

      - name: Run k6 forward label test
        run: ./k6 run --config config.json load_tests_scripts/as_uswest_qa_phv3_post_shipment.js
